version: v1.0.0
# kratos is the username
# kratosBOY is the password (should change that)
# 127.0.0.1:5432/kratos is the database location 

dsn: postgres://kratos:kratosBOY@127.0.0.1:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  public:
    base_url: http://127.0.0.1:4433/
    host: 127.0.0.1
    cors:
      allowed_origins:
        - https://yourdomain.com
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
      enabled: true
      debug: true
  admin:
    base_url: http://kratos:4434/
    host: 127.0.0.1

selfservice:
  default_browser_return_url: https://yourdomain.com
  allowed_return_urls:
    - https://yourdomain.com

  methods:
    password:
      enabled: true
    profile:
      enabled: true
    oidc:
      config:
        providers:
          - id: google # this is `<provider-id>` in the Authorization callback URL. DO NOT CHANGE IT ONCE SET!
            provider: google
            client_id: client_id (for google oidc authentication)
            client_secret: client_secret (for google oidc authentication)
            mapper_url: "file:///(ADD YOUR LOCTION HERE <--)/schemas/oidc.google.jsonnet"
            # Alternatively, use an URL:
            # mapper_url: https://storage.googleapis.com/abc-cde-prd/9cac9717f007808bf17f22ce7f4295c739604b183f05ac4afb4
            scope:
              - email
              - profile
            # other supported scopes can be found in Google OAuth 2.0 dev docs
            requested_claims:
              id_token:
                email:
                  essential: true
                email_verified:
                  essential: true
                given_name:
                  essential: true
                family_name: null
                hd: null # If you want the Google Workspace domain
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: https://yourdomain.com/error

    settings:
      ui_url: https://yourdomain.com/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: https://yourdomain.com/recovery
      use: code

    verification:
      enabled: true
      ui_url: https://yourdomain.com/verification
      use: code
      after:
        default_browser_return_url: https://yourdomain.com/

    logout:
      after:
        default_browser_return_url: https://yourdomain.com/login

    login:
      ui_url: https://yourdomain.com/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://yourdomain.com/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui
        oidc:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: debug
  format: text
  leak_sensitive_values: true

session:
  lifespan: 72h
  cookie:
    domain: yourdomain.com

secrets:
  cookie:
    - cookie (ADD ME I NEED A cookie)
  cipher:
    - cipher (ADD ME I NEED A cipher)

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///(ADD YOUR LOCTION HERE <--)/config/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
